AWSTemplateFormatVersion: 2010-09-09
Description: 'make an instance, based on region, ami, subnet, and security group'
Parameters:
  KeyName:
    Description: Name of and existing EC2 KeyPair to enable SSH access to the instance
    Type: String
  VpcId:
    Type: String
    Description: VpcId of your existing Virtual Private Cloud (VPC)
  SubnetId:
    Type: String
    Description: SubnetId of an existing subnet in your Virtual Private Cloud (VPC)
  AmiId:
    Type: String
    Description: AMI You want to use
  SecurityGroupId:
    Type: String
    Description: SecurityGroup to use
Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref AmiId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      SubnetId: !Ref SubnetId
      KeyName: !Ref KeyName
Outputs:
  InstanceId:
    Value: !Ref Ec2Instance
    Description: Instance ID of newly created instance