AWSTemplateFormatVersion: 2010-09-09
Description: Creates an empty SQL Server RDS database as an example for automated deployments.
Parameters:
  SqlServerInstanceName:
    NoEcho: 'false'
    Description: RDS SQL Server Instance Name
    Type: String
    Default: SqlRdsDB
    MinLength: '1'
    MaxLength: '63'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
  DatabaseUsername:
    AllowedPattern: '[a-zA-Z0-9]+'
    ConstraintDescription: Must contain only alphanumeric characters.
    Description: The database admin account user name.
    MaxLength: '16'
    MinLength: '1'
    Type: String
  DatabasePassword:
    AllowedPattern: '^(?=.*[0-9])(?=.*[a-zA-Z])([a-zA-Z0-9]+)'
    ConstraintDescription: Must contain only alphanumeric characters with at least one capital letter and one number.
    Description: The database admin account password.
    MaxLength: '41'
    MinLength: '8'
    NoEcho: 'true'
    Type: String
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: 'SQL Instance name, master username and password'
        Parameters:
          - SqlServerInstanceName
          - DatabaseUsername
          - DatabasePassword
        ParameterLabels:
          SqlServerInstanceName:
            default: Instance name
          DatabaseUsername:
            default: Master user name
          DatabasePassword:
            default: Password
  'AWS::CloudFormation::Designer':
    cd86009b-a0f4-4640-b60d-37cf9b3d234b:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 90
      z: 1
      embeds: []
    4829fee3-0052-4699-9ea2-4e73eaaa79db:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 90
      z: 1
      embeds: []
      dependson:
        - cd86009b-a0f4-4640-b60d-37cf9b3d234b
Resources:
  SQLServerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: SQL Server Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '1433'
          ToPort: '1433'
          CidrIp: 0.0.0.0/0
    Metadata:
      'AWS::CloudFormation::Designer':
        id: cd86009b-a0f4-4640-b60d-37cf9b3d234b
  SQLDatabase:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      VPCSecurityGroups:
        - 'Fn::GetAtt':
            - SQLServerSecurityGroup
            - GroupId
      DBInstanceIdentifier:
        Ref: SqlServerInstanceName
      LicenseModel: license-included
      Engine: sqlserver-ex
      EngineVersion: 14.00.1000.169
      MultiAZ: false
      DBInstanceClass: db.t2.micro
      AllocatedStorage: '20'
      MasterUsername:
        Ref: DatabaseUsername
      MasterUserPassword:
        Ref: DatabasePassword
      PubliclyAccessible: 'true'
      Tags:
        - Key: Name
          Value: sqlmaster
        - Key: project
          Value: development unittest
      BackupRetentionPeriod: '1'
    DependsOn: SQLServerSecurityGroup
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 4829fee3-0052-4699-9ea2-4e73eaaa79db
Outputs:
  SQLDatabaseEndpoint:
    Description: Database endpoint
    Value: !Sub '${SQLDatabase.Endpoint.Address}:${SQLDatabase.Endpoint.Port}'