AWSTemplateFormatVersion: 2010-09-09
Description: Creates an empty SQL Server RDS database as an example for automated deployments.
Parameters:
  SqlServerInstanceName:
    NoEcho: 'false'
    Description: RDS SQL Server Instance Name
    Type: String
    Default: SqlRdsDB
    MinLength: '1'
    MaxLength: '63'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
  DatabaseUsername:
    AllowedPattern: '[a-zA-Z0-9]+'
    ConstraintDescription: Must contain only alphanumeric characters.
    Description: The database admin account user name.
    MaxLength: '16'
    MinLength: '1'
    Type: String
  DatabasePassword:
    AllowedPattern: '^(?=.*[0-9])(?=.*[a-zA-Z])([a-zA-Z0-9]+)'
    ConstraintDescription: Must contain only alphanumeric characters with at least one capital letter and one number.
    Description: The database admin account password.
    MaxLength: '41'
    MinLength: '8'
    NoEcho: 'true'
    Type: String
  VPCSecurityGroup:
    Description: The VPC Security Group.
    MaxLength: '256'
    MinLength: '9'
    Type: String
  DBSubnetGroup:
    Description: DB Subnet Group in RDS.
    MaxLength: '256'
    MinLength: '9'
    Type: String
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: 'SQL Instance name, master username and password'
        Parameters:
          - SqlServerInstanceName
          - DatabaseUsername
          - DatabasePassword
          - VPCSecurityGroup
          - DBSubnetGroup
        ParameterLabels:
          SqlServerInstanceName:
            default: Instance name
          DatabaseUsername:
            default: Master user name
          DatabasePassword:
            default: Password
          VPCSecurityGroup:
            default: VPC Security Group
          DBSubnetGroup:
            default: DB Subnet Group
  'AWS::CloudFormation::Designer':
    cd86009b-a0f4-4640-b60d-37cf9b3d234b:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 90
      z: 1
      embeds: []
    4829fee3-0052-4699-9ea2-4e73eaaa79db:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 90
      z: 1
      embeds: []
      dependson:
        - cd86009b-a0f4-4640-b60d-37cf9b3d234b
Resources:
  SQLDatabase:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBSubnetGroupName: 
        Ref: DBSubnetGroup
      VPCSecurityGroups: 
        - Ref: VPCSecurityGroup
      DBInstanceIdentifier:
        Ref: SqlServerInstanceName
      LicenseModel: license-included
      Engine: sqlserver-ex
      EngineVersion: 14.00.1000.169.v1
      MultiAZ: false
      DBInstanceClass: db.t2.micro
      AllocatedStorage: '20'
      MasterUsername:
        Ref: DatabaseUsername
      MasterUserPassword:
        Ref: DatabasePassword
      PubliclyAccessible: 'false'
      Tags:
        - Key: Name
          Value: sqlmaster
        - Key: project
          Value: development unittest
      BackupRetentionPeriod: '1'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 4829fee3-0052-4699-9ea2-4e73eaaa79db
Outputs:
  SQLDatabaseEndpoint:
    Description: Database endpoint
    Value: !Sub '${SQLDatabase.Endpoint.Address}:${SQLDatabase.Endpoint.Port}'