AWSTemplateFormatVersion: '2010-09-09'
Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/sammysoftware/vpc_template.yaml
      TimeoutInMinutes: '60'
Outputs:
  VpcStackRef:
    Value: !Ref VpcStack
  VpcStackVpcId:
    Value: !GetAtt VpcStack.Outputs.VPCID
  VpcStackPublicSubnet:
    Value: !GetAtt VpcStack.Outputs.PublicSubnet1ID
  VpcStackDBSubnetGroup:
    Value: !GetAtt VpcStack.Outputs.DBSubnetGroupID